modLoader = "javafml"
loaderVersion = "[43,)"
license = "All rights reserved"
[[mods]]
logoFile = "block_rummage.png"
modId = "block_rummage"
version = "${file.jarVersion}"
displayName = "Block Rummage"
authors = "Sammy;"
description = '''
A cool mod for digging things up!.
'''
[[dependencies.block_rummage]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.block_rummage]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"